openapi: 3.1.0
info:
  title: BitNodes-Snapshot
  description: |-
    This API fetches the snapshot of the active nodes of the bitcoin network.

     Some useful links:
     - [BitNodes API Documentation](https://bitnodes.io/api/)
  version: 1.0.0
externalDocs:
  description: Find out more about Bitnodes
  url: https://bitnodes.io/
servers:
  - url: https://bitnodes.io/api/v1/snapshots/
paths:
  /latest:
    get:
      tags: -latest
      summary: Fetch the latest network snapshot
